### PR TITLE
WIP Add an ellipsoid for the Moon

### PR DESCRIPTION
**Pull request by leouieda**
Use values from the compilation in [Wieczorek (2015)](https://doi.org/10.1016/B978-0-444-53802-4.00169-X).

**Reminders**

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst`.
- [ ] Write detailed docstrings for all functions/methods.
- [ ] If adding new functionality, add an example to the docstring, gallery, and/or tutorials.

### CODE REVIEW

**Comment by leouieda** [comment]
Tests fail because the equations fail (nan) when the flattening is 0. That leads to eccentricities being 0 and there are divisions of these values in the equations. The only sensible way forward I can see is to create a separate `Sphere` class that has simplified equations for a reference sphere. It would actually be a lot simpler since we'd be using spherical coordinates by default and so wouldn't need the coordinate conversions. The gravity equations is also a lot simpler.

**Comment by leouieda** [comment]
Maybe a better way forward is to check if the flattening is close to zero and then use the sphere equation instead. That way we don’t need a new class and the associated maintenance.

**Comment by santisoler** [comment]
I have updated this PR by defining the `MOON` ellipsoids as an instance of the new `Sphere` class introduced on #42.
I faced a bug on how the `Sphere` class computes the gravity on the equator, which should be fixed on #48.
After that, I think the Moon implementation should be ready, maybe we could add a gallery example for it.

**Comment by leouieda** [comment]
Closing this since the approach wouldn't work. See #53 instead.

**Pull request closed without merging**
