### PR TITLE
Add attributes for the normal potential to Sphere and Ellipsoid

### PR DESCRIPTION
**Pull request by MarkWieczorek**
This PR adds the property `reference_potential` to the Ellipsoid class. This is $U_0$ as defined by eq 2-123 in Hofmann-Wellenhof and Moritz.

This quantity is required in any application where it is necessary to compute the height of the geoid above the reference ellipsoid. I verified that the value of the GRS80 ellipsoid is what is in the above book.

As part of this PR, I corrected a couple minor typos:
* The linear eccentricity was given the mathematical symbol E in the docstring (as opposed to "c" which has several other meanings)
* The volume of an ellipsoid was defined using "c" instead of "b" in the docstring.

**Note:**
I did not add `reference_potential` to the Sphere class. This is because (as noted in the docs), the surface of a rotating sphere does not correspond to an equipotential.

We could perhaps instead add
```
Sphere.reference_gravitational_potential = GM/R
```
I'm happy to add if others think this is useful. GM/R appears everywhere when working with gravity fields of bodies like the Moon, so maybe it would be useful.

**Relevant issues/PRs:**
Relevant to #151

### CODE REVIEW

**Comment by leouieda** [comment]
Thanks for this @MarkWieczorek! Should we call this `surface_gravity_potential` instead? Makes it clear that it's not gravitational and is on the surface. Then the Sphere one could `surface_gravitational_potential`. If you find that it appears in calculations for you, then please feel free to add it.

**Comment by MarkWieczorek** [comment]
Not sure which is best:

`reference_gravity_potential`
`reference_gravitational_potential`

or

`surface_gravity_potential`
`surface_gravitational_potential`

Let me think about this, unless someone want to make an executive decision.

**Comment by leouieda** [comment]
No rush. I'm OK with either one.

**Comment by leouieda** [comment]
😆 alright by me. And yes, it would be great to allow creating the `Ellipsoid` in multiple ways. It just makes the attribute validation logic harder but it should be doable.

**Pull request merged**
