### PR TITLE
Tests normal gravity against Somigliana equation

### PR DESCRIPTION
**Pull request by santisoler**
Add tests functions to compare ellipsoids' normal gravity on their surface against the Somigliana equation.

**Reminders**:

- [ ] Run `make format` and `make check` to make sure the code follows the style guide.
- [ ] Add tests for new features or tests that would have caught the bug that you're fixing.
- [ ] Add new public functions/methods/classes to `doc/api/index.rst` and the base `__init__.py` file for the package.
- [ ] Write detailed docstrings for all functions/classes/methods. It often helps to design better code if you write the docstrings first.
- [ ] If adding new functionality, add an example to the docstring, gallery, and/or tutorials.
- [ ] Add your full name, affiliation, and [ORCID](https://orcid.org) (optional) to the `AUTHORS.md` file (if you haven't already) in case you'd like to be listed as an author on the [Zenodo](https://zenodo.org/communities/fatiando) archive of the next release.

### CODE REVIEW

**Comment by leouieda** [comment]
@santisoler I made a few changes here: mostly moved the function to a `boule/tests/utils.py` module and made some adjustments to the function (calculating sin and cos only once).

**Comment by leouieda** [comment]
We could remove the sphere test from this branch so we can merge it with tests passing. Then we can implement it in #52 so that we're confident that we can fix the sphere gravity. What do you think?

**Comment by santisoler** [comment]
> We could remove the sphere test from this branch so we can merge it with tests passing. Then we can implement it in #52 so that we're confident that we can fix the sphere gravity. What do you think?

I agree. I will move the Somigliana test on the sphere to #52.

Thanks for the modifications, they are way better than what I drafted yesterday.

**Comment by leouieda** [comment]
👍🏽 feel free to merge whenever you're ready

**Pull request merged**
