### PR TITLE
Add a logo for Boule

### PR DESCRIPTION
**Pull request by leouieda**
**Description**

Created a logo on Boule based on initial designs by @aguspesce. It's made up of some rotated ellipses with our Earth logo in the middle. I tried making them concentric ellipses but it looked bad as a logo. This PR adds the logo files, README banner, and includes the logo in the documentation page.

readme-banner

readme-banner

### CODE REVIEW

**Comment by leouieda** [comment]
Some feedback would be much appreciated. The source SVG files are in this branch as well if anyone want to play around with them.

**Comment by Esteban82** [comment]
> Some feedback would be much appreciated. The source SVG files are in this branch as well if anyone want to play around with them.

What about if you rotate the world of the logo to put Brazil (and South America) in the center of globe?

**Comment by leouieda** [comment]
@Esteban82 thanks for the suggestion! I would be a bit of work to do that since the world there is the stylized map from the Fatiando logo. Plus, I wouldn't want to remove our African friends.

**Comment by aguspesce** [comment]
I love it!

**Comment by leouieda** [comment]
Alright, merging this in. Further tweaks and changes are welcome in follow up PRs!

**Comment by MGomezN** [comment]
> @Esteban82, thanks for the suggestion! It would be a bit of work to do that since the world there is the stylized map from the Fatiando logo. Plus, I wouldn't want to remove our African friends.

But what about our Mexican friends in Baja, California? 🥲
Jeje was just kidding. It looks very nice... I will ask Abraham for a 3D animation of the Fatiando Logo where all the friends on Earth are included so we can avoid future Fatiando territory wars.

**Pull request merged**
